default: &default
  adapter: postgresql
  host: 127.0.0.1
  pool: 5
  username: postgres
  password: son332000
  reconnect: false
  encoding: utf8

development:
  <<: *default
  database: exam_development

test:
  <<: *default
  database: exam_test
